import { InjectRepository } from '@nestjs/typeorm';
import {
	ApplicationStatus,
	ApplicantStatus,
	UserRole,
	VacancyStatus,
} from 'src/common/enum';
import { Department } from 'src/entities/department.entity';
import { Repository } from 'typeorm';
import * as bcrypt from 'bcrypt';
import { User } from 'src/entities/user.entity';
import { Vacancy } from 'src/entities/vacancy.entity';
import { Applicant } from 'src/entities/applicant.entity';
import { Employee } from 'src/entities/employee.entity';
import { Application } from 'src/entities/application.entity';
import { randomInt } from 'crypto';
import { Injectable } from '@nestjs/common';

@Injectable()
export class Seed {
	constructor(
		@InjectRepository(Department)
		private departmentTable: Repository<Department>,
		@InjectRepository(User)
		private userTable: Repository<User>,
		@InjectRepository(Vacancy)
		private vacancyTable: Repository<Vacancy>,
		@InjectRepository(Application)
		private applicationTable: Repository<Application>,
	) {}

	private departments = [
		{ name: 'Engineering' },
		{ name: 'Marketing' },
		{ name: 'Sales' },
		{ name: 'HR' },
		{ name: 'Finance' },
		{ name: 'Design' },
	];

	/* ------------------------------------------------------------------ */
	/*  Users – 32 total (1 admin, 5 HR, 6 interviewers, 20 applicants)    */
	/*  NOTE: id is auto-generated by TypeORM; do NOT set it manually.     */
	/* ------------------------------------------------------------------ */

	private readonly defaultPassword = bcrypt.hashSync('123456', 10);

	private initialUsers = [
		{ fullName: UserRole.SUPER_ADMIN, role: UserRole.SUPER_ADMIN, email: 'admin@test.com', phone: '0901234567', isVerified: true },
		{ fullName: UserRole.HR, role: UserRole.HR, email: 'hr@test.com', phone: '0901234568', isVerified: true },
		{ fullName: UserRole.INTERVIEWER, role: UserRole.INTERVIEWER, email: 'interviewer@test.com', phone: '0901234569', isVerified: true },
		{ fullName: UserRole.APPLICANT, role: UserRole.APPLICANT, email: 'applicant@test.com', phone: '0901234570', isVerified: true },
		{ fullName: `${UserRole.INTERVIEWER} 2`, role: UserRole.INTERVIEWER, email: 'interviewer2@gmail.com', phone: '0901234571', isVerified: true },
		{ fullName: `${UserRole.HR} 2`, role: UserRole.HR, email: 'hr2@gmail.com', phone: '0912345678', isVerified: true },
		{ fullName: 'Bui Duc Manh', role: UserRole.INTERVIEWER, email: 'manh.bui@gmail.com', phone: '0923456789', isVerified: true },
		{ fullName: 'Nguyen Thi Hoa', role: UserRole.APPLICANT, email: 'hoa.nguyen@gmail.com', phone: '0934567890', isVerified: true },
		{ fullName: 'Dang Van Khoa', role: UserRole.APPLICANT, email: 'khoa.dang@gmail.com', phone: '0945678901', isVerified: true },
		{ fullName: 'Ly Thi Mai', role: UserRole.APPLICANT, email: 'mai.ly@gmail.com', phone: '0956789012', isVerified: true },
		{ fullName: 'Tran Van Nam', role: UserRole.APPLICANT, email: 'nam.tran@gmail.com', phone: '0967890123', isVerified: true },
		{ fullName: 'Phan Thi Oanh', role: UserRole.INTERVIEWER, email: 'oanh.phan@gmail.com', phone: '0978901234', isVerified: true },
	];

	/* 15 extra applicants */
	private extraApplicants = [
		{ fullName: 'Le Van An', email: 'an.le@gmail.com', phone: '0981111222' },
		{ fullName: 'Hoang Thi Bich', email: 'bich.hoang@gmail.com', phone: '0981111223' },
		{ fullName: 'Pham Van Cuong', email: 'cuong.pham@gmail.com', phone: '0981111224' },
		{ fullName: 'Vu Thi Dung', email: 'dung.vu@gmail.com', phone: '0981111225' },
		{ fullName: 'Do Van Em', email: 'em.do@gmail.com', phone: '0981111226' },
		{ fullName: 'Ngo Thi Phuong', email: 'phuong.ngo@gmail.com', phone: '0981111227' },
		{ fullName: 'Trinh Van Giap', email: 'giap.trinh@gmail.com', phone: '0981111228' },
		{ fullName: 'Mai Thi Huong', email: 'huong.mai@gmail.com', phone: '0981111229' },
		{ fullName: 'Dinh Van Ich', email: 'ich.dinh@gmail.com', phone: '0981111230' },
		{ fullName: 'Phung Thi Kieu', email: 'kieu.phung@gmail.com', phone: '0981111231' },
		{ fullName: 'Duong Van Long', email: 'long.duong@gmail.com', phone: '0981111232' },
		{ fullName: 'Cao Thi Minh', email: 'minh.cao@gmail.com', phone: '0981111233' },
		{ fullName: 'Ha Van Nhat', email: 'nhat.ha@gmail.com', phone: '0981111234' },
		{ fullName: 'Ninh Thi Quyen', email: 'quyen.ninh@gmail.com', phone: '0981111235' },
		{ fullName: 'Thach Van Sang', email: 'sang.thach@gmail.com', phone: '0981111236' },
	];

	/* 3 extra HR + 2 extra interviewers */
	private extraStaff = [
		{ fullName: 'Tran Thanh Tung', role: UserRole.HR, email: 'tung.tran@company.com', phone: '0977000111' },
		{ fullName: 'Le Ngoc Lan', role: UserRole.HR, email: 'lan.le@company.com', phone: '0977000112' },
		{ fullName: 'Nguyen Hoang Phuc', role: UserRole.HR, email: 'phuc.nguyen@company.com', phone: '0977000113' },
		{ fullName: 'Vo Minh Tuan', role: UserRole.INTERVIEWER, email: 'tuan.vo@company.com', phone: '0977000114' },
		{ fullName: 'Truong Thi Thuy', role: UserRole.INTERVIEWER, email: 'thuy.truong@company.com', phone: '0977000115' },
	];

	private buildAllUsers() {
		const users: Array<{
			fullName: string;
			role: UserRole;
			email: string;
			phone: string;
			password: string;
			isVerified: boolean;
		}> = [];

		for (const u of this.initialUsers) {
			users.push({ ...u, password: this.defaultPassword });
		}
		for (const u of this.extraApplicants) {
			users.push({ ...u, role: UserRole.APPLICANT, password: this.defaultPassword, isVerified: true });
		}
		for (const u of this.extraStaff) {
			users.push({ ...u, password: this.defaultPassword, isVerified: true });
		}

		return users;
	}

	/* ------------------------------------------------------------------ */
	/*  Vacancies – 20 total                                              */
	/*  createdByEmail → looked up at seed-time to get real DB id.        */
	/* ------------------------------------------------------------------ */

	private initialVacancies = [
		{ title: 'Senior Frontend Developer', description: 'React/TypeScript expert with 3+ years. Strong knowledge of State Management, Testing and CI/CD.', departmentId: 1, numberOfOpenings: 2, createdByEmail: 'admin@test.com', status: VacancyStatus.OPENED },
		{ title: 'Marketing Manager', description: 'Manage online/offline marketing strategy. 5+ years, proficient in Google Ads, Facebook Ads and SEO.', departmentId: 2, numberOfOpenings: 1, createdByEmail: 'admin@test.com', status: VacancyStatus.OPENED },
		{ title: 'Sales Executive', description: 'B2B sales, strong negotiation and presentation skills. IT industry experience preferred.', departmentId: 3, numberOfOpenings: 3, createdByEmail: 'hr@test.com', status: VacancyStatus.OPENED },
		{ title: 'UX Designer', description: 'User experience design, proficient in Figma, with real portfolio.', departmentId: 6, numberOfOpenings: 1, createdByEmail: 'hr@test.com', status: VacancyStatus.CLOSED },
		{ title: 'Finance Analyst', description: 'Financial analysis, reporting, forecasting. CFA Level 1+ is a plus.', departmentId: 5, numberOfOpenings: 2, createdByEmail: 'admin@test.com', status: VacancyStatus.SUSPENDED },
		{ title: 'Backend Engineer', description: 'API development, microservices. Node.js/NestJS, PostgreSQL, Docker required.', departmentId: 1, numberOfOpenings: 2, createdByEmail: 'hr@test.com', status: VacancyStatus.OPENED },
		{ title: 'HR Business Partner', description: 'HR strategy consulting, support departments in recruitment and people development.', departmentId: 4, numberOfOpenings: 1, createdByEmail: 'admin@test.com', status: VacancyStatus.OPENED },
		{ title: 'DevOps Engineer', description: 'Cloud infrastructure (AWS/GCP), CI/CD pipelines, monitoring. Kubernetes experience is a plus.', departmentId: 1, numberOfOpenings: 1, createdByEmail: 'hr@test.com', status: VacancyStatus.OPENED },
	];

	private extraVacancies = [
		{ title: 'Full-stack Developer', description: 'React + Node.js, GraphQL, PostgreSQL. 2+ years experience.', departmentId: 1, numberOfOpenings: 3, createdByEmail: 'admin@test.com', status: VacancyStatus.OPENED },
		{ title: 'QA Engineer', description: 'Manual & automation testing. Selenium/Cypress, API testing with Postman.', departmentId: 1, numberOfOpenings: 2, createdByEmail: 'admin@test.com', status: VacancyStatus.OPENED },
		{ title: 'Data Engineer', description: 'ETL pipelines, Apache Spark, Airflow, SQL/NoSQL databases.', departmentId: 1, numberOfOpenings: 1, createdByEmail: 'hr@test.com', status: VacancyStatus.OPENED },
		{ title: 'Content Marketing Specialist', description: 'SEO content writing, blog management, email campaigns.', departmentId: 2, numberOfOpenings: 2, createdByEmail: 'hr2@gmail.com', status: VacancyStatus.OPENED },
		{ title: 'Social Media Manager', description: 'Facebook, TikTok, Instagram strategy. Analytics-driven.', departmentId: 2, numberOfOpenings: 1, createdByEmail: 'hr2@gmail.com', status: VacancyStatus.OPENED },
		{ title: 'Business Development Executive', description: 'Lead generation, partnership building, CRM management.', departmentId: 3, numberOfOpenings: 2, createdByEmail: 'hr@test.com', status: VacancyStatus.OPENED },
		{ title: 'Recruitment Specialist', description: 'End-to-end recruitment, employer branding, ATS experience.', departmentId: 4, numberOfOpenings: 2, createdByEmail: 'hr2@gmail.com', status: VacancyStatus.OPENED },
		{ title: 'Accountant', description: 'General ledger, tax reporting, SAP/QuickBooks experience.', departmentId: 5, numberOfOpenings: 1, createdByEmail: 'admin@test.com', status: VacancyStatus.OPENED },
		{ title: 'Graphic Designer', description: 'Adobe Creative Suite, branding, print & digital assets.', departmentId: 6, numberOfOpenings: 1, createdByEmail: 'hr@test.com', status: VacancyStatus.OPENED },
		{ title: 'Product Designer', description: 'UI/UX for SaaS products, design systems, prototyping.', departmentId: 6, numberOfOpenings: 1, createdByEmail: 'hr@test.com', status: VacancyStatus.OPENED },
		{ title: 'IT Support Specialist', description: 'Helpdesk, network troubleshooting, Windows/Linux administration.', departmentId: 1, numberOfOpenings: 2, createdByEmail: 'admin@test.com', status: VacancyStatus.OPENED },
		{ title: 'Payroll Officer', description: 'Payroll processing, labor law compliance, Excel proficiency.', departmentId: 5, numberOfOpenings: 1, createdByEmail: 'hr2@gmail.com', status: VacancyStatus.OPENED },
	];

	private buildAllVacancies() {
		const now = new Date().toISOString().split('T')[0];
		const all: any[] = [];

		for (const v of this.initialVacancies) {
			all.push({
				...v,
				filledCount: 0,
				closingDate: this.randomClosingDate(),
				createdAt: now,
				updatedAt: now,
			});
		}
		for (const v of this.extraVacancies) {
			all.push({
				...v,
				filledCount: 0,
				closingDate: this.randomClosingDate(),
				createdAt: now,
				updatedAt: now,
			});
		}

		return all;
	}

	private randomClosingDate() {
		return new Date(Date.now() + Math.floor(Math.random() * 30 + 5) * 86400000)
			.toISOString()
			.split('T')[0];
	}

	/**
	 * Pick a random item from an array.
	 */
	private pickRandom<T>(arr: T[]): T {
		return arr[randomInt(0, arr.length)];
	}

	/* ------------------------------------------------------------------ */
	/*  Seed methods                                                      */
	/* ------------------------------------------------------------------ */

	async seedUser(): Promise<Map<string, User>> {
		const userMap = new Map<string, User>();
		const users = this.buildAllUsers();
		let created = 0;
		let existed = 0;

		for (const user of users) {
			await this.userTable.manager.transaction(async (manager) => {
				const existing = await manager.findOne(User, {
					where: { email: user.email },
				});
				if (existing) {
					userMap.set(user.email, existing);
					existed++;
					return;
				}

				let newUser = manager.create(User, user);
				newUser = await manager.save(newUser);

				userMap.set(user.email, newUser);
				created++;

				switch (newUser.role) {
					case UserRole.APPLICANT: {
						const applicant = manager.create(Applicant, { user: newUser });
						newUser.applicant = applicant;
						await manager.save(applicant);
						await manager.save(newUser);
						break;
					}
					case UserRole.SUPER_ADMIN:
						break;
					default: {
						const employee = manager.create(Employee, { user: newUser });
						employee.isActive = true;
						employee.department = { id: randomInt(1, 6) } as Department;
						newUser.employee = employee;
						await manager.save(employee);
						await manager.save(newUser);
						break;
					}
				}
			});
		}

		await this.userTable.query(`
			SELECT setval(
				pg_get_serial_sequence('users', 'id'),
				(SELECT MAX(id) FROM users)
			);
		`);

		console.log(`✅ Users: ${created} created, ${existed} already existed`);
		return userMap;
	}

	async seedDepartment() {
		let created = 0;
		for (const dept of this.departments) {
			const exists = await this.departmentTable.findOne({
				where: { name: dept.name },
			});
			if (!exists) {
				await this.departmentTable.save(dept);
				created++;
			}
		}

		await this.departmentTable.query(`
			SELECT setval(
				pg_get_serial_sequence('departments', 'id'),
				(SELECT MAX(id) FROM departments)
			);
		`);

		console.log(`✅ Departments: ${created} created, ${this.departments.length - created} already existed`);
	}

	async seedVacancy(userMap: Map<string, User>) {
		const vacancies = this.buildAllVacancies();
		let created = 0;
		let skipped = 0;

		for (const vac of vacancies) {
			const exists = await this.vacancyTable.findOne({
				where: {
					title: vac.title,
					departmentId: vac.departmentId,
				},
			});
			if (!exists) {
				const creator = userMap.get(vac.createdByEmail);
				if (!creator) {
					console.warn(`⚠️  Vacancy "${vac.title}" references unknown email "${vac.createdByEmail}" – skipping.`);
					skipped++;
					continue;
				}

				const { createdByEmail, ...vacData } = vac;
				await this.vacancyTable.save({
					...vacData,
					createdById: creator.id,
				});
				created++;
			}
		}

		await this.vacancyTable.query(`
			SELECT setval(
				pg_get_serial_sequence('vacancies', 'id'),
				(SELECT MAX(id) FROM vacancies)
			);
		`);

		console.log(`✅ Vacancies: ${created} created, ${skipped} skipped`);
	}

	/**
	 * For each applicant, randomly assign 1–2 vacancies.
	 * This produces ~30 applications with varied statuses and no duplicates.
	 */
	async seedApplication() {
		const allUsers = await this.userTable.find({
			where: { role: UserRole.APPLICANT },
			relations: ['applicant'],
			order: { id: 'ASC' },
		});

		const allVacancies = await this.vacancyTable.find({
			order: { id: 'ASC' },
		});
		const currentSelectedCounts = await this.applicationTable
			.createQueryBuilder('application')
			.select('application.vacancyId', 'vacancyId')
			.addSelect('COUNT(*)', 'count')
			.where('application.status = :status', {
				status: ApplicationStatus.SELECTED,
			})
			.groupBy('application.vacancyId')
			.getRawMany<{ vacancyId: number; count: string }>();
		const selectedByVacancy = new Map(
			currentSelectedCounts.map((item) => [
				Number(item.vacancyId),
				Number(item.count),
			]),
		);

		const applicantList = allUsers.filter((u) => u.applicant != null);
		const statuses: ApplicationStatus[] = [
			ApplicationStatus.PENDING,
			ApplicationStatus.PENDING,
			ApplicationStatus.PENDING,
			ApplicationStatus.PENDING,
			ApplicationStatus.PENDING,
			ApplicationStatus.INTERVIEW_SCHEDULED,
			ApplicationStatus.INTERVIEW_SCHEDULED,
			ApplicationStatus.PENDING_REVIEW,
			ApplicationStatus.SELECTED,
			ApplicationStatus.REJECTED,
			ApplicationStatus.NOT_REQUIRED,
		];

		let created = 0;

		for (const user of applicantList) {
			const count = randomInt(1, 3);
			const picked = new Set<number>();

			for (let i = 0; i < count; i++) {
				const vacancy = this.pickRandom(allVacancies);
				if (picked.has(vacancy.id)) continue;
				picked.add(vacancy.id);

				const exists = await this.applicationTable.findOne({
					where: {
						applicantId: user.applicant!.id,
						vacancyId: vacancy.id,
					},
				});

				if (!exists) {
					let status = this.pickRandom(statuses);
					if (status === ApplicationStatus.SELECTED) {
						const selectedCount = selectedByVacancy.get(vacancy.id) ?? 0;
						if (selectedCount >= vacancy.numberOfOpenings) {
							status = ApplicationStatus.PENDING_REVIEW;
						} else {
							selectedByVacancy.set(vacancy.id, selectedCount + 1);
						}
					}
					const app = this.applicationTable.create({
						applicantId: user.applicant!.id,
						vacancyId: vacancy.id,
						status,
						hrNotes: '',
					});
					await this.applicationTable.save(app);
					created++;
				}
			}
		}

		await this.applicationTable.query(`
			SELECT setval(
				pg_get_serial_sequence('applications', 'id'),
				(SELECT MAX(id) FROM applications)
			);
		`);

		await this.syncApplicationDerivedState();

		console.log(`✅ Applications: ${created} created`);
	}

	private async syncApplicationDerivedState() {
		const vacancyCounts = await this.applicationTable
			.createQueryBuilder('application')
			.select('application.vacancyId', 'vacancyId')
			.addSelect('COUNT(*)', 'count')
			.where('application.status = :status', {
				status: ApplicationStatus.SELECTED,
			})
			.groupBy('application.vacancyId')
			.getRawMany<{ vacancyId: number; count: string }>();
		const countsByVacancy = new Map(
			vacancyCounts.map((item) => [
				Number(item.vacancyId),
				Number(item.count),
			]),
		);

		const vacancies = await this.vacancyTable.find();
		for (const vacancy of vacancies) {
			vacancy.filledCount = countsByVacancy.get(vacancy.id) ?? 0;
			if (vacancy.filledCount >= vacancy.numberOfOpenings) {
				vacancy.status = VacancyStatus.CLOSED;
			}
			await this.vacancyTable.save(vacancy);
		}

		const activeApplications = await this.applicationTable
			.createQueryBuilder('application')
			.select('DISTINCT application.applicantId', 'applicantId')
			.getRawMany<{ applicantId: number }>();
		const activeApplicantIds = activeApplications.map((item) =>
			Number(item.applicantId),
		);
		if (activeApplicantIds.length) {
			await this.applicationTable.manager
				.createQueryBuilder()
				.update(Applicant)
				.set({ status: ApplicantStatus.IN_PROCESS })
				.where('id IN (:...ids)', { ids: activeApplicantIds })
				.execute();
		}

		const selectedApplications = await this.applicationTable
			.createQueryBuilder('application')
			.select('DISTINCT application.applicantId', 'applicantId')
			.where('application.status = :status', {
				status: ApplicationStatus.SELECTED,
			})
			.getRawMany<{ applicantId: number }>();
		const selectedApplicantIds = selectedApplications.map((item) =>
			Number(item.applicantId),
		);
		if (selectedApplicantIds.length) {
			await this.applicationTable.manager
				.createQueryBuilder()
				.update(Applicant)
				.set({ status: ApplicantStatus.HIRED })
				.where('id IN (:...ids)', { ids: selectedApplicantIds })
				.execute();
		}
	}

	async runSeed() {
		console.log('🌱 Seed started...');
		await this.seedDepartment();
		const userMap = await this.seedUser();
		await this.seedVacancy(userMap);
		await this.seedApplication();
		console.log('✅ Seed completed!');
	}
}
