import { InjectRepository } from '@nestjs/typeorm';
import {
	ApplicationStatus,
	ApplicantStatus,
	UserRole,
	VacancyStatus,
} from 'src/common/enum';
import { Department } from 'src/entities/department.entity';
import { Repository } from 'typeorm';
import * as bcrypt from 'bcrypt';
import { User } from 'src/entities/user.entity';
import { Vacancy } from 'src/entities/vacancy.entity';
import { Applicant } from 'src/entities/applicant.entity';
import { Employee } from 'src/entities/employee.entity';
import { Application } from 'src/entities/application.entity';
import { randomInt } from 'crypto';
import { Injectable } from '@nestjs/common';

@Injectable()
export class Seed {
	constructor(
		@InjectRepository(Department)
		private departmentTable: Repository<Department>,
		@InjectRepository(User)
		private userTable: Repository<User>,
		@InjectRepository(Vacancy)
		private vacancyTable: Repository<Vacancy>,
		@InjectRepository(Application)
		private applicationTable: Repository<Application>,
	) { }

	private departments = [
		{ name: 'Engineering' },
		{ name: 'Marketing' },
		{ name: 'Sales' },
		{ name: 'HR' },
		{ name: 'Finance' },
		{ name: 'Design' },
	];

	/* ------------------------------------------------------------------ */
	/* Users – 32 total (1 admin, 5 HR, 6 interviewers, 20 applicants)    */
	/* NOTE: id is auto-generated by TypeORM; do NOT set it manually.     */
	/* ------------------------------------------------------------------ */

	private readonly defaultPassword = bcrypt.hashSync('123456', 10);

	private initialUsers = [
		{ fullName: UserRole.SUPER_ADMIN, role: UserRole.SUPER_ADMIN, email: 'admin@test.com', phone: '0901234567', isVerified: true },
		{ fullName: UserRole.HR, role: UserRole.HR, email: 'hr@test.com', phone: '0901234568', isVerified: true },
		{ fullName: UserRole.INTERVIEWER, role: UserRole.INTERVIEWER, email: 'interviewer@test.com', phone: '0901234569', isVerified: true },
		{ fullName: UserRole.APPLICANT, role: UserRole.APPLICANT, email: 'applicant@test.com', phone: '0901234570', isVerified: true },
		{ fullName: `${UserRole.INTERVIEWER} 2`, role: UserRole.INTERVIEWER, email: 'interviewer2@gmail.com', phone: '0901234571', isVerified: true },
		{ fullName: `${UserRole.HR} 2`, role: UserRole.HR, email: 'hr2@gmail.com', phone: '0912345678', isVerified: true },
		{ fullName: 'Bui Duc Manh', role: UserRole.INTERVIEWER, email: 'manh.bui@gmail.com', phone: '0923456789', isVerified: true },
		{ fullName: 'Nguyen Thi Hoa', role: UserRole.APPLICANT, email: 'hoa.nguyen@gmail.com', phone: '0934567890', isVerified: true },
		{ fullName: 'Dang Van Khoa', role: UserRole.APPLICANT, email: 'khoa.dang@gmail.com', phone: '0945678901', isVerified: true },
		{ fullName: 'Ly Thi Mai', role: UserRole.APPLICANT, email: 'mai.ly@gmail.com', phone: '0956789012', isVerified: true },
		{ fullName: 'Tran Van Nam', role: UserRole.APPLICANT, email: 'nam.tran@gmail.com', phone: '0967890123', isVerified: true },
		{ fullName: 'Phan Thi Oanh', role: UserRole.INTERVIEWER, email: 'oanh.phan@gmail.com', phone: '0978901234', isVerified: true },
	];

	/* 15 extra applicants */
	private extraApplicants = [
		{ fullName: 'Le Van An', email: 'an.le@gmail.com', phone: '0981111222' },
		{ fullName: 'Hoang Thi Bich', email: 'bich.hoang@gmail.com', phone: '0981111223' },
		{ fullName: 'Pham Van Cuong', email: 'cuong.pham@gmail.com', phone: '0981111224' },
		{ fullName: 'Vu Thi Dung', email: 'dung.vu@gmail.com', phone: '0981111225' },
		{ fullName: 'Do Van Em', email: 'em.do@gmail.com', phone: '0981111226' },
		{ fullName: 'Ngo Thi Phuong', email: 'phuong.ngo@gmail.com', phone: '0981111227' },
		{ fullName: 'Trinh Van Giap', email: 'giap.trinh@gmail.com', phone: '0981111228' },
		{ fullName: 'Mai Thi Huong', email: 'huong.mai@gmail.com', phone: '0981111229' },
		{ fullName: 'Dinh Van Ich', email: 'ich.dinh@gmail.com', phone: '0981111230' },
		{ fullName: 'Phung Thi Kieu', email: 'kieu.phung@gmail.com', phone: '0981111231' },
		{ fullName: 'Duong Van Long', email: 'long.duong@gmail.com', phone: '0981111232' },
		{ fullName: 'Cao Thi Minh', email: 'minh.cao@gmail.com', phone: '0981111233' },
		{ fullName: 'Ha Van Nhat', email: 'nhat.ha@gmail.com', phone: '0981111234' },
		{ fullName: 'Ninh Thi Quyen', email: 'quyen.ninh@gmail.com', phone: '0981111235' },
		{ fullName: 'Thach Van Sang', email: 'sang.thach@gmail.com', phone: '0981111236' },
	];

	/* 3 extra HR + 2 extra interviewers */
	private extraStaff = [
		{ fullName: 'Tran Thanh Tung', role: UserRole.HR, email: 'tung.tran@company.com', phone: '0977000111' },
		{ fullName: 'Le Ngoc Lan', role: UserRole.HR, email: 'lan.le@company.com', phone: '0977000112' },
		{ fullName: 'Nguyen Hoang Phuc', role: UserRole.HR, email: 'phuc.nguyen@company.com', phone: '0977000113' },
		{ fullName: 'Vo Minh Tuan', role: UserRole.INTERVIEWER, email: 'tuan.vo@company.com', phone: '0977000114' },
		{ fullName: 'Truong Thi Thuy', role: UserRole.INTERVIEWER, email: 'thuy.truong@company.com', phone: '0977000115' },
	];

	private buildAllUsers() {
		const users: Array<{
			fullName: string;
			role: UserRole;
			email: string;
			phone: string;
			password: string;
			isVerified: boolean;
		}> = [];

		for (const u of this.initialUsers) {
			users.push({ ...u, password: this.defaultPassword });
		}
		for (const u of this.extraApplicants) {
			users.push({ ...u, role: UserRole.APPLICANT, password: this.defaultPassword, isVerified: true });
		}
		for (const u of this.extraStaff) {
			users.push({ ...u, password: this.defaultPassword, isVerified: true });
		}

		return users;
	}

	/* ------------------------------------------------------------------ */
	/* Vacancies – 20 total                                              */
	/* createdByEmail → looked up at seed-time to get real DB id.        */
	/* ------------------------------------------------------------------ */

	private initialVacancies = [
		{
			title: 'Senior Frontend Developer',
			description: `The Global Innovation Centre is part of our Enterprise Operations division. Our mission is to connect top local talent with world-class projects to build products that impact millions of users globally.
We are focused on delivering exceptional customer experiences by leveraging modern technologies and fostering a culture of engineering and operational excellence.

The Role: As a Senior Frontend Developer, you will lead the development of highly responsive and accessible web applications, ensuring top-tier performance and robust state management. You will work closely with global partners and cross-functional teams to drive innovation.

We're investing in you: We strive to create a workplace where you can thrive, learn, and elevate those around you. We believe in people with ideas and dreams!

Core Skills & Technologies:
TypeScript, React, Redux, HTML5/CSS3

Testing & Tools:
Jest, Cypress, Webpack, Vite, CI/CD pipelines

Collaboration:
Microsoft Outlook, JIRA, Confluence, Microsoft Teams, Zoom`,
			departmentId: 1, numberOfOpenings: 2, createdByEmail: 'admin@test.com', status: VacancyStatus.OPENED
		},
		{
			title: 'Marketing Manager',
			description: `The Global Innovation Centre is part of our Enterprise Operations division. Our mission is to connect top local talent with world-class projects to build products that impact millions of users globally.
We are focused on delivering exceptional customer experiences by leveraging modern technologies and fostering a culture of operational excellence.

The Role: As a Marketing Manager, you will manage online and offline marketing strategies, orchestrating cross-channel campaigns to maximize ROI and brand awareness. You will work closely with global partners and cross-functional teams to drive innovation.

We're investing in you: We strive to create a workplace where you can thrive, learn, and elevate those around you. We believe in people with ideas and dreams!

Core Skills & Technologies:
Google Ads, Facebook Ads, SEO/SEM strategies, Brand Management

Testing & Tools:
Google Analytics, HubSpot, Salesforce CRM

Collaboration:
Microsoft Outlook, JIRA, Confluence, Microsoft Teams, Zoom`,
			departmentId: 2, numberOfOpenings: 1, createdByEmail: 'admin@test.com', status: VacancyStatus.OPENED
		},
		{
			title: 'Sales Executive',
			description: `The Global Innovation Centre is part of our Enterprise Operations division. Our mission is to connect top local talent with world-class projects to build products that impact millions of users globally.
We are focused on delivering exceptional customer experiences by leveraging modern technologies and fostering a culture of operational excellence.

The Role: As a Sales Executive, you will drive B2B sales, utilizing strong negotiation and presentation skills to build lasting relationships with enterprise clients in the IT sector. You will work closely with global partners and cross-functional teams to drive innovation.

We're investing in you: We strive to create a workplace where you can thrive, learn, and elevate those around you. We believe in people with ideas and dreams!

Core Skills & Technologies:
B2B Sales, Negotiation, Lead Generation, Client Relationship Management

Testing & Tools:
Salesforce, HubSpot CRM, LinkedIn Sales Navigator

Collaboration:
Microsoft Outlook, JIRA, Confluence, Microsoft Teams, Zoom`,
			departmentId: 3, numberOfOpenings: 3, createdByEmail: 'hr@test.com', status: VacancyStatus.OPENED
		},
		{
			title: 'UX Designer',
			description: `The Global Innovation Centre is part of our Enterprise Operations division. Our mission is to connect top local talent with world-class projects to build products that impact millions of users globally.
We are focused on delivering exceptional customer experiences by leveraging modern technologies and fostering a culture of engineering and operational excellence.

The Role: As a UX Designer, you will shape the user experience by creating intuitive user flows, wireframes, and prototypes, translating complex requirements into elegant designs. You will work closely with global partners and cross-functional teams to drive innovation.

We're investing in you: We strive to create a workplace where you can thrive, learn, and elevate those around you. We believe in people with ideas and dreams!

Core Skills & Technologies:
User Research, Wireframing, Prototyping, Interaction Design

Testing & Tools:
Figma, Sketch, Adobe XD, InVision

Collaboration:
Microsoft Outlook, JIRA, Confluence, Microsoft Teams, Zoom`,
			departmentId: 6, numberOfOpenings: 1, createdByEmail: 'hr@test.com', status: VacancyStatus.CLOSED
		},
		{
			title: 'Finance Analyst',
			description: `The Global Innovation Centre is part of our Enterprise Operations division. Our mission is to connect top local talent with world-class projects to build products that impact millions of users globally.
We are focused on delivering exceptional customer experiences by leveraging modern technologies and fostering a culture of operational excellence.

The Role: As a Finance Analyst, you will conduct in-depth financial analysis, reporting, and forecasting to guide strategic business decisions. CFA Level 1+ is highly preferred. You will work closely with global partners and cross-functional teams to drive innovation.

We're investing in you: We strive to create a workplace where you can thrive, learn, and elevate those around you. We believe in people with ideas and dreams!

Core Skills & Technologies:
Financial Modeling, ROI Analysis, Cash Flow Forecasting, Corporate Finance

Testing & Tools:
SAP/ERP Systems, QuickBooks, Advanced MS Excel, PowerBI

Collaboration:
Microsoft Outlook, JIRA, Confluence, Microsoft Teams, Zoom`,
			departmentId: 5, numberOfOpenings: 2, createdByEmail: 'admin@test.com', status: VacancyStatus.SUSPENDED
		},
		{
			title: 'Backend Engineer',
			description: `The Global Innovation Centre is part of our Enterprise Operations division. Our mission is to connect top local talent with world-class projects to build products that impact millions of users globally.
We are focused on delivering exceptional customer experiences by leveraging modern technologies and fostering a culture of engineering and operational excellence.

The Role: As a Backend Engineer, you will design and develop robust APIs and event-driven microservices, ensuring high availability and secure data processing. You will work closely with global partners and cross-functional teams to drive innovation.

We're investing in you: We strive to create a workplace where you can thrive, learn, and elevate those around you. We believe in people with ideas and dreams!

Core Skills & Technologies:
Node.js, NestJS, PostgreSQL, REST/GraphQL APIs

Testing & Tools:
Docker, Postman, Jest, Swagger

Collaboration:
Microsoft Outlook, JIRA, Confluence, Microsoft Teams, Zoom`,
			departmentId: 1, numberOfOpenings: 2, createdByEmail: 'hr@test.com', status: VacancyStatus.OPENED
		},
		{
			title: 'HR Business Partner',
			description: `The Global Innovation Centre is part of our Enterprise Operations division. Our mission is to connect top local talent with world-class projects to build products that impact millions of users globally.
We are focused on delivering exceptional customer experiences by leveraging modern technologies and fostering a culture of operational excellence.

The Role: As an HR Business Partner, you will provide strategic HR consulting, supporting technical departments in talent acquisition, performance management, and employee retention. You will work closely with global partners and cross-functional teams to drive innovation.

We're investing in you: We strive to create a workplace where you can thrive, learn, and elevate those around you. We believe in people with ideas and dreams!

Core Skills & Technologies:
Talent Management, Employee Relations, Performance Management, Labor Laws

Testing & Tools:
Workday, BambooHR, LinkedIn Recruiter

Collaboration:
Microsoft Outlook, JIRA, Confluence, Microsoft Teams, Zoom`,
			departmentId: 4, numberOfOpenings: 1, createdByEmail: 'admin@test.com', status: VacancyStatus.OPENED
		},
		{
			title: 'DevOps Engineer',
			description: `The Global Innovation Centre is part of our Enterprise Operations division. Our mission is to connect top local talent with world-class projects to build products that impact millions of users globally.
We are focused on delivering exceptional customer experiences by leveraging modern technologies and fostering a culture of engineering and operational excellence.

The Role: As a DevOps Engineer, you will manage cloud infrastructure, build reliable CI/CD pipelines, and implement comprehensive monitoring and alerting systems. You will work closely with global partners and cross-functional teams to drive innovation.

We're investing in you: We strive to create a workplace where you can thrive, learn, and elevate those around you. We believe in people with ideas and dreams!

Core Skills & Technologies:
Cloud Infrastructure (AWS/GCP), CI/CD pipelines, Containerization

Testing & Tools:
Kubernetes, Docker, Jenkins, Terraform, Prometheus, Grafana

Collaboration:
Microsoft Outlook, JIRA, Confluence, Microsoft Teams, Zoom`,
			departmentId: 1, numberOfOpenings: 1, createdByEmail: 'hr@test.com', status: VacancyStatus.OPENED
		},
	];

	private extraVacancies = [
		{
			title: 'Full-stack Developer',
			description: `The Global Innovation Centre is part of our Enterprise Operations division. Our mission is to connect top local talent with world-class projects to build products that impact millions of users globally.
We are focused on delivering exceptional customer experiences by leveraging modern technologies and fostering a culture of engineering and operational excellence.

The Role: As a Full-stack Developer, you will build end-to-end features, architecting databases and crafting seamless user interfaces for our core SaaS products. You will work closely with global partners and cross-functional teams to drive innovation.

We're investing in you: We strive to create a workplace where you can thrive, learn, and elevate those around you. We believe in people with ideas and dreams!

Core Skills & Technologies:
React, Node.js, GraphQL, PostgreSQL, TypeScript

Testing & Tools:
Docker, Jest, Webpack, CI/CD pipelines

Collaboration:
Microsoft Outlook, JIRA, Confluence, Microsoft Teams, Zoom`,
			departmentId: 1, numberOfOpenings: 3, createdByEmail: 'admin@test.com', status: VacancyStatus.OPENED
		},
		{
			title: 'QA Engineer',
			description: `The Global Innovation Centre is part of our Enterprise Operations division. Our mission is to connect top local talent with world-class projects to build products that impact millions of users globally.
We are focused on delivering exceptional customer experiences by leveraging modern technologies and fostering a culture of engineering and operational excellence.

The Role: As a QA Engineer, you will ensure product excellence through comprehensive manual and automated testing, working closely with developers to catch issues early. You will work closely with global partners and cross-functional teams to drive innovation.

We're investing in you: We strive to create a workplace where you can thrive, learn, and elevate those around you. We believe in people with ideas and dreams!

Core Skills & Technologies:
Manual & Automation Testing, API Testing, Test Case Management

Testing & Tools:
Selenium, Cypress, Postman, JMeter

Collaboration:
Microsoft Outlook, JIRA, Confluence, Microsoft Teams, Zoom`,
			departmentId: 1, numberOfOpenings: 2, createdByEmail: 'admin@test.com', status: VacancyStatus.OPENED
		},
		{
			title: 'Data Engineer',
			description: `The Global Innovation Centre is part of our Enterprise Operations division. Our mission is to connect top local talent with world-class projects to build products that impact millions of users globally.
We are focused on delivering exceptional customer experiences by leveraging modern technologies and fostering a culture of engineering and operational excellence.

The Role: As a Data Engineer, you will build and optimize ETL pipelines, process large-scale datasets, and maintain robust database architectures for our analytics teams. You will work closely with global partners and cross-functional teams to drive innovation.

We're investing in you: We strive to create a workplace where you can thrive, learn, and elevate those around you. We believe in people with ideas and dreams!

Core Skills & Technologies:
ETL pipelines, SQL/NoSQL databases, Data Warehousing, Python

Testing & Tools:
Apache Spark, Airflow, Hadoop, Snowflake

Collaboration:
Microsoft Outlook, JIRA, Confluence, Microsoft Teams, Zoom`,
			departmentId: 1, numberOfOpenings: 1, createdByEmail: 'hr@test.com', status: VacancyStatus.OPENED
		},
		{
			title: 'Content Marketing Specialist',
			description: `The Global Innovation Centre is part of our Enterprise Operations division. Our mission is to connect top local talent with world-class projects to build products that impact millions of users globally.
We are focused on delivering exceptional customer experiences by leveraging modern technologies and fostering a culture of operational excellence.

The Role: As a Content Marketing Specialist, you will drive engagement through SEO-optimized content writing, blog management, and targeted email marketing campaigns. You will work closely with global partners and cross-functional teams to drive innovation.

We're investing in you: We strive to create a workplace where you can thrive, learn, and elevate those around you. We believe in people with ideas and dreams!

Core Skills & Technologies:
SEO Content Writing, Blog Management, Email Campaigns, Copywriting

Testing & Tools:
WordPress, Mailchimp, Google Analytics, Ahrefs

Collaboration:
Microsoft Outlook, JIRA, Confluence, Microsoft Teams, Zoom`,
			departmentId: 2, numberOfOpenings: 2, createdByEmail: 'hr2@gmail.com', status: VacancyStatus.OPENED
		},
		{
			title: 'Social Media Manager',
			description: `The Global Innovation Centre is part of our Enterprise Operations division. Our mission is to connect top local talent with world-class projects to build products that impact millions of users globally.
We are focused on delivering exceptional customer experiences by leveraging modern technologies and fostering a culture of operational excellence.

The Role: As a Social Media Manager, you will craft and execute analytics-driven strategies across major platforms to build community engagement and brand loyalty. You will work closely with global partners and cross-functional teams to drive innovation.

We're investing in you: We strive to create a workplace where you can thrive, learn, and elevate those around you. We believe in people with ideas and dreams!

Core Skills & Technologies:
Facebook, TikTok, Instagram Strategy, Community Management

Testing & Tools:
Hootsuite, Sprout Social, Social Media Analytics

Collaboration:
Microsoft Outlook, JIRA, Confluence, Microsoft Teams, Zoom`,
			departmentId: 2, numberOfOpenings: 1, createdByEmail: 'hr2@gmail.com', status: VacancyStatus.OPENED
		},
		{
			title: 'Business Development Executive',
			description: `The Global Innovation Centre is part of our Enterprise Operations division. Our mission is to connect top local talent with world-class projects to build products that impact millions of users globally.
We are focused on delivering exceptional customer experiences by leveraging modern technologies and fostering a culture of operational excellence.

The Role: As a Business Development Executive, you will focus on lead generation, identifying new market opportunities, and building strategic partnerships. You will work closely with global partners and cross-functional teams to drive innovation.

We're investing in you: We strive to create a workplace where you can thrive, learn, and elevate those around you. We believe in people with ideas and dreams!

Core Skills & Technologies:
Lead Generation, Partnership Building, Pipeline Management, B2B Strategies

Testing & Tools:
Salesforce CRM, LinkedIn Sales Navigator, Outreach

Collaboration:
Microsoft Outlook, JIRA, Confluence, Microsoft Teams, Zoom`,
			departmentId: 3, numberOfOpenings: 2, createdByEmail: 'hr@test.com', status: VacancyStatus.OPENED
		},
		{
			title: 'Recruitment Specialist',
			description: `The Global Innovation Centre is part of our Enterprise Operations division. Our mission is to connect top local talent with world-class projects to build products that impact millions of users globally.
We are focused on delivering exceptional customer experiences by leveraging modern technologies and fostering a culture of operational excellence.

The Role: As a Recruitment Specialist, you will manage the end-to-end recruitment lifecycle, enhance employer branding, and ensure a stellar candidate experience. You will work closely with global partners and cross-functional teams to drive innovation.

We're investing in you: We strive to create a workplace where you can thrive, learn, and elevate those around you. We believe in people with ideas and dreams!

Core Skills & Technologies:
End-to-end Recruitment, Sourcing, Interviewing, Employer Branding

Testing & Tools:
Applicant Tracking Systems (ATS), LinkedIn Recruiter, Boolean Search

Collaboration:
Microsoft Outlook, JIRA, Confluence, Microsoft Teams, Zoom`,
			departmentId: 4, numberOfOpenings: 2, createdByEmail: 'hr2@gmail.com', status: VacancyStatus.OPENED
		},
		{
			title: 'Accountant',
			description: `The Global Innovation Centre is part of our Enterprise Operations division. Our mission is to connect top local talent with world-class projects to build products that impact millions of users globally.
We are focused on delivering exceptional customer experiences by leveraging modern technologies and fostering a culture of operational excellence.

The Role: As an Accountant, you will manage the general ledger, ensure tax reporting compliance, and maintain accurate financial records for the organization. You will work closely with global partners and cross-functional teams to drive innovation.

We're investing in you: We strive to create a workplace where you can thrive, learn, and elevate those around you. We believe in people with ideas and dreams!

Core Skills & Technologies:
General Ledger, Tax Reporting, Reconciliation, Financial Accounting

Testing & Tools:
SAP, QuickBooks, Advanced Excel, Xero

Collaboration:
Microsoft Outlook, JIRA, Confluence, Microsoft Teams, Zoom`,
			departmentId: 5, numberOfOpenings: 1, createdByEmail: 'admin@test.com', status: VacancyStatus.OPENED
		},
		{
			title: 'Graphic Designer',
			description: `The Global Innovation Centre is part of our Enterprise Operations division. Our mission is to connect top local talent with world-class projects to build products that impact millions of users globally.
We are focused on delivering exceptional customer experiences by leveraging modern technologies and fostering a culture of operational excellence.

The Role: As a Graphic Designer, you will create compelling visual assets for print and digital channels, reinforcing our brand identity across all marketing materials. You will work closely with global partners and cross-functional teams to drive innovation.

We're investing in you: We strive to create a workplace where you can thrive, learn, and elevate those around you. We believe in people with ideas and dreams!

Core Skills & Technologies:
Branding, Typography, Visual Identity, Digital & Print Assets

Testing & Tools:
Adobe Creative Suite (Photoshop, Illustrator, InDesign)

Collaboration:
Microsoft Outlook, JIRA, Confluence, Microsoft Teams, Zoom`,
			departmentId: 6, numberOfOpenings: 1, createdByEmail: 'hr@test.com', status: VacancyStatus.OPENED
		},
		{
			title: 'Product Designer',
			description: `The Global Innovation Centre is part of our Enterprise Operations division. Our mission is to connect top local talent with world-class projects to build products that impact millions of users globally.
We are focused on delivering exceptional customer experiences by leveraging modern technologies and fostering a culture of engineering and operational excellence.

The Role: As a Product Designer, you will craft the UI/UX for our SaaS products, building scalable design systems and delivering high-fidelity interactive prototypes. You will work closely with global partners and cross-functional teams to drive innovation.

We're investing in you: We strive to create a workplace where you can thrive, learn, and elevate those around you. We believe in people with ideas and dreams!

Core Skills & Technologies:
UI/UX Design, Design Systems, Prototyping, Interaction Design

Testing & Tools:
Figma, Sketch, Zeplin, InVision

Collaboration:
Microsoft Outlook, JIRA, Confluence, Microsoft Teams, Zoom`,
			departmentId: 6, numberOfOpenings: 1, createdByEmail: 'hr@test.com', status: VacancyStatus.OPENED
		},
		{
			title: 'IT Support Specialist',
			description: `The Global Innovation Centre is part of our Enterprise Operations division. Our mission is to connect top local talent with world-class projects to build products that impact millions of users globally.
We are focused on delivering exceptional customer experiences by leveraging modern technologies and fostering a culture of engineering and operational excellence.

The Role: As an IT Support Specialist, you will provide critical helpdesk support, troubleshoot network issues, and administer internal IT infrastructure. You will work closely with global partners and cross-functional teams to drive innovation.

We're investing in you: We strive to create a workplace where you can thrive, learn, and elevate those around you. We believe in people with ideas and dreams!

Core Skills & Technologies:
Helpdesk, Network Troubleshooting, Systems Administration

Testing & Tools:
Windows/Linux OS, Active Directory, ServiceNow, Zendesk

Collaboration:
Microsoft Outlook, JIRA, Confluence, Microsoft Teams, Zoom`,
			departmentId: 1, numberOfOpenings: 2, createdByEmail: 'admin@test.com', status: VacancyStatus.OPENED
		},
		{
			title: 'Payroll Officer',
			description: `The Global Innovation Centre is part of our Enterprise Operations division. Our mission is to connect top local talent with world-class projects to build products that impact millions of users globally.
We are focused on delivering exceptional customer experiences by leveraging modern technologies and fostering a culture of operational excellence.

The Role: As a Payroll Officer, you will process payroll accurately and on time, ensuring strict compliance with labor laws and company policies. You will work closely with global partners and cross-functional teams to drive innovation.

We're investing in you: We strive to create a workplace where you can thrive, learn, and elevate those around you. We believe in people with ideas and dreams!

Core Skills & Technologies:
Payroll Processing, Labor Law Compliance, Compensation & Benefits

Testing & Tools:
Payroll Software, Advanced Excel, HRIS integration

Collaboration:
Microsoft Outlook, JIRA, Confluence, Microsoft Teams, Zoom`,
			departmentId: 5, numberOfOpenings: 1, createdByEmail: 'hr2@gmail.com', status: VacancyStatus.OPENED
		},
	];

	private buildAllVacancies() {
		const now = new Date().toISOString().split('T')[0];
		const all: any[] = [];

		for (const v of this.initialVacancies) {
			all.push({
				...v,
				filledCount: 0,
				closingDate: this.randomClosingDate(),
				createdAt: now,
				updatedAt: now,
			});
		}
		for (const v of this.extraVacancies) {
			all.push({
				...v,
				filledCount: 0,
				closingDate: this.randomClosingDate(),
				createdAt: now,
				updatedAt: now,
			});
		}

		return all;
	}

	private randomClosingDate() {
		return new Date(Date.now() + Math.floor(Math.random() * 30 + 5) * 86400000)
			.toISOString()
			.split('T')[0];
	}

	/**
	 * Pick a random item from an array.
	 */
	private pickRandom<T>(arr: T[]): T {
		return arr[randomInt(0, arr.length)];
	}

	/* ------------------------------------------------------------------ */
	/* Seed methods                                                      */
	/* ------------------------------------------------------------------ */

	async seedUser(): Promise<Map<string, User>> {
		const userMap = new Map<string, User>();
		const users = this.buildAllUsers();
		let created = 0;
		let existed = 0;

		for (const user of users) {
			await this.userTable.manager.transaction(async (manager) => {
				const existing = await manager.findOne(User, {
					where: { email: user.email },
				});
				if (existing) {
					userMap.set(user.email, existing);
					existed++;
					return;
				}

				let newUser = manager.create(User, user);
				newUser = await manager.save(newUser);

				userMap.set(user.email, newUser);
				created++;

				switch (newUser.role) {
					case UserRole.APPLICANT: {
						const applicant = manager.create(Applicant, { user: newUser });
						newUser.applicant = applicant;
						await manager.save(applicant);
						await manager.save(newUser);
						break;
					}
					case UserRole.SUPER_ADMIN:
						break;
					default: {
						const employee = manager.create(Employee, { user: newUser });
						employee.isActive = true;
						employee.department = { id: randomInt(1, 6) } as Department;
						newUser.employee = employee;
						await manager.save(employee);
						await manager.save(newUser);
						break;
					}
				}
			});
		}

		await this.userTable.query(`
			SELECT setval(
				pg_get_serial_sequence('users', 'id'),
				(SELECT MAX(id) FROM users)
			);
		`);

		console.log(`✅ Users: ${created} created, ${existed} already existed`);
		return userMap;
	}

	async seedDepartment() {
		let created = 0;
		for (const dept of this.departments) {
			const exists = await this.departmentTable.findOne({
				where: { name: dept.name },
			});
			if (!exists) {
				await this.departmentTable.save(dept);
				created++;
			}
		}

		await this.departmentTable.query(`
			SELECT setval(
				pg_get_serial_sequence('departments', 'id'),
				(SELECT MAX(id) FROM departments)
			);
		`);

		console.log(`✅ Departments: ${created} created, ${this.departments.length - created} already existed`);
	}

	async seedVacancy(userMap: Map<string, User>) {
		const vacancies = this.buildAllVacancies();
		let created = 0;
		let skipped = 0;

		for (const vac of vacancies) {
			const exists = await this.vacancyTable.findOne({
				where: {
					title: vac.title,
					departmentId: vac.departmentId,
				},
			});
			if (!exists) {
				const creator = userMap.get(vac.createdByEmail);
				if (!creator) {
					console.warn(`⚠️  Vacancy "${vac.title}" references unknown email "${vac.createdByEmail}" – skipping.`);
					skipped++;
					continue;
				}

				const { createdByEmail, ...vacData } = vac;
				await this.vacancyTable.save({
					...vacData,
					createdById: creator.id,
				});
				created++;
			}
		}

		await this.vacancyTable.query(`
			SELECT setval(
				pg_get_serial_sequence('vacancies', 'id'),
				(SELECT MAX(id) FROM vacancies)
			);
		`);

		console.log(`✅ Vacancies: ${created} created, ${skipped} skipped`);
	}

	/**
	 * For each applicant, randomly assign 1–2 vacancies.
	 * This produces ~30 applications with varied statuses and no duplicates.
	 */
	async seedApplication() {
		const allUsers = await this.userTable.find({
			where: { role: UserRole.APPLICANT },
			relations: ['applicant'],
			order: { id: 'ASC' },
		});

		const allVacancies = await this.vacancyTable.find({
			order: { id: 'ASC' },
		});
		const currentSelectedCounts = await this.applicationTable
			.createQueryBuilder('application')
			.select('application.vacancyId', 'vacancyId')
			.addSelect('COUNT(*)', 'count')
			.where('application.status = :status', {
				status: ApplicationStatus.SELECTED,
			})
			.groupBy('application.vacancyId')
			.getRawMany<{ vacancyId: number; count: string }>();
		const selectedByVacancy = new Map(
			currentSelectedCounts.map((item) => [
				Number(item.vacancyId),
				Number(item.count),
			]),
		);

		const applicantList = allUsers.filter((u) => u.applicant != null);
		const statuses: ApplicationStatus[] = [
			ApplicationStatus.PENDING,
			ApplicationStatus.PENDING,
			ApplicationStatus.PENDING,
			ApplicationStatus.PENDING,
			ApplicationStatus.PENDING,
			ApplicationStatus.INTERVIEW_SCHEDULED,
			ApplicationStatus.INTERVIEW_SCHEDULED,
			ApplicationStatus.PENDING_REVIEW,
			ApplicationStatus.SELECTED,
			ApplicationStatus.REJECTED,
			ApplicationStatus.NOT_REQUIRED,
		];

		let created = 0;

		for (const user of applicantList) {
			const count = randomInt(1, 3);
			const picked = new Set<number>();

			for (let i = 0; i < count; i++) {
				const vacancy = this.pickRandom(allVacancies);
				if (picked.has(vacancy.id)) continue;
				picked.add(vacancy.id);

				const exists = await this.applicationTable.findOne({
					where: {
						applicantId: user.applicant!.id,
						vacancyId: vacancy.id,
					},
				});

				if (!exists) {
					let status = this.pickRandom(statuses);
					if (status === ApplicationStatus.SELECTED) {
						const selectedCount = selectedByVacancy.get(vacancy.id) ?? 0;
						if (selectedCount >= vacancy.numberOfOpenings) {
							status = ApplicationStatus.PENDING_REVIEW;
						} else {
							selectedByVacancy.set(vacancy.id, selectedCount + 1);
						}
					}
					const app = this.applicationTable.create({
						applicantId: user.applicant!.id,
						vacancyId: vacancy.id,
						status,
						hrNotes: '',
					});
					await this.applicationTable.save(app);
					created++;
				}
			}
		}

		await this.applicationTable.query(`
			SELECT setval(
				pg_get_serial_sequence('applications', 'id'),
				(SELECT MAX(id) FROM applications)
			);
		`);

		await this.syncApplicationDerivedState();

		console.log(`✅ Applications: ${created} created`);
	}

	private async syncApplicationDerivedState() {
		const vacancyCounts = await this.applicationTable
			.createQueryBuilder('application')
			.select('application.vacancyId', 'vacancyId')
			.addSelect('COUNT(*)', 'count')
			.where('application.status = :status', {
				status: ApplicationStatus.SELECTED,
			})
			.groupBy('application.vacancyId')
			.getRawMany<{ vacancyId: number; count: string }>();
		const countsByVacancy = new Map(
			vacancyCounts.map((item) => [
				Number(item.vacancyId),
				Number(item.count),
			]),
		);

		const vacancies = await this.vacancyTable.find();
		for (const vacancy of vacancies) {
			vacancy.filledCount = countsByVacancy.get(vacancy.id) ?? 0;
			if (vacancy.filledCount >= vacancy.numberOfOpenings) {
				vacancy.status = VacancyStatus.CLOSED;
			}
			await this.vacancyTable.save(vacancy);
		}

		const activeApplications = await this.applicationTable
			.createQueryBuilder('application')
			.select('DISTINCT application.applicantId', 'applicantId')
			.getRawMany<{ applicantId: number }>();
		const activeApplicantIds = activeApplications.map((item) =>
			Number(item.applicantId),
		);
		if (activeApplicantIds.length) {
			await this.applicationTable.manager
				.createQueryBuilder()
				.update(Applicant)
				.set({ status: ApplicantStatus.IN_PROCESS })
				.where('id IN (:...ids)', { ids: activeApplicantIds })
				.execute();
		}

		const selectedApplications = await this.applicationTable
			.createQueryBuilder('application')
			.select('DISTINCT application.applicantId', 'applicantId')
			.where('application.status = :status', {
				status: ApplicationStatus.SELECTED,
			})
			.getRawMany<{ applicantId: number }>();
		const selectedApplicantIds = selectedApplications.map((item) =>
			Number(item.applicantId),
		);
		if (selectedApplicantIds.length) {
			await this.applicationTable.manager
				.createQueryBuilder()
				.update(Applicant)
				.set({ status: ApplicantStatus.HIRED })
				.where('id IN (:...ids)', { ids: selectedApplicantIds })
				.execute();
		}
	}

	async runSeed() {
		console.log('🌱 Seed started...');
		await this.seedDepartment();
		const userMap = await this.seedUser();
		await this.seedVacancy(userMap);
		await this.seedApplication();
		console.log('✅ Seed completed!');
	}
}