export const USER_ROLES = {
  SUPERADMIN: 'SUPERADMIN',
  HR: 'HR',
  INTERVIEWER: 'INTERVIEWER',
  HIRING_MANAGER: 'HIRING_MANAGER',
  ADMIN: 'ADMIN',
  APPLICANT: 'APPLICANT',
} as const;

export const MANAGED_USER_ROLES = [USER_ROLES.HR, USER_ROLES.INTERVIEWER];
